name: PDD linter
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]
jobs:
  pdd-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Install pdd
        run: |
          gem install pdd
      - name: Puzzles
        run: pdd --file=/dev/null